import { useState, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { useNavigate, Link } from 'react-router-dom'
import { useRegisterMutation, useGetDepartmentsQuery } from './authApi.js'
import { setCredentials } from './authSlice.js'

const Register = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    department: '',
    role: 'employee',
  })
  const [generatedEmployeeId, setGeneratedEmployeeId] = useState('')
  const [errors, setErrors] = useState({})

  const dispatch = useDispatch()
  const navigate = useNavigate()
  const { user } = useSelector((state) => state.auth)
  const [register, { isLoading }] = useRegisterMutation()
  const { data: departmentsData, isLoading: departmentsLoading } = useGetDepartmentsQuery()

  // Generate preview employee ID based on role
  useEffect(() => {
    const generatePreviewId = () => {
      const rolePrefix = formData.role === 'manager' ? 'MGR' : 'EMP'
      // Generate a preview ID (actual ID will be generated by backend)
      const timestamp = Date.now().toString().slice(-4)
      setGeneratedEmployeeId(`${rolePrefix}${timestamp}`)
    }
    generatePreviewId()
  }, [formData.role])

  useEffect(() => {
    if (user) {
      navigate(user.role === 'manager' ? '/manager/dashboard' : '/employee/dashboard')
    }
  }, [user, navigate])

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value })
    setErrors({ ...errors, [e.target.name]: '' })
  }

  const validate = () => {
    const newErrors = {}
    if (!formData.name || formData.name.trim() === '') {
      newErrors.name = 'Name is required'
    }
    if (!formData.email || formData.email.trim() === '') {
      newErrors.email = 'Email is required'
    }
    if (!formData.password || formData.password.length < 6) {
      newErrors.password = 'Password must be at least 6 characters'
    }
    if (!formData.department || formData.department.trim() === '') {
      newErrors.department = 'Department is required'
    }
    return newErrors
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    const validationErrors = validate()
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors)
      return
    }

    try {
      // Don't send employeeId - backend will generate it automatically
      const { employeeId, ...submitData } = formData
      const result = await register(submitData).unwrap()
      dispatch(
        setCredentials({
          user: result.data,
          accessToken: result.data.accessToken,
        })
      )
      navigate(result.data.role === 'manager' ? '/manager/dashboard' : '/employee/dashboard')
    } catch (err) {
      setErrors({ submit: err.data?.message || 'Registration failed. Please try again.' })
    }
  }

  return (
    <div className="min-h-screen flex">
      {/* Left Panel - Purple Gradient */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-[#4a148c] to-[#7c43bd] text-white p-12 flex-col relative overflow-hidden">
        <div className="relative z-10 h-full flex flex-col">
          <div>
            <Link to="/" className="inline-flex items-center text-sm text-purple-200 hover:text-white transition-colors">
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Back to Home
            </Link>
          </div>

          <div className="mt-20">
            <div className="inline-flex items-center px-3 py-1 rounded-full border border-purple-400/30 bg-purple-500/20 text-purple-100 text-xs font-medium mb-8">
              <svg className="w-3 h-3 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
              </svg>
              New Account Setup
            </div>

            <h1 className="text-5xl font-bold mb-6 leading-tight tracking-tight">
              Join the Team<br />
              at TAP Academy.
            </h1>

            <p className="text-purple-200 text-lg max-w-md leading-relaxed">
              Create your profile to access development tools, attendance tracking, and internal resources.
            </p>
          </div>

          <div className="mt-auto">
            <p className="text-sm text-purple-300">
              © {new Date().getFullYear()} Tap Academy. All rights reserved.
            </p>
          </div>
        </div>

        {/* Decorative gradients */}
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-purple-500/30 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-96 h-96 bg-indigo-500/30 rounded-full blur-3xl"></div>
      </div>

      {/* Right Panel - Registration Form */}
      <div className="flex-1 flex items-center justify-center bg-white p-4 sm:px-6 lg:px-8">
        <div className="max-w-xl w-full space-y-8">
          <div className="text-center">
            <div className="mx-auto h-16 w-16 bg-purple-50 rounded-2xl flex items-center justify-center mb-6">
              <svg className="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z" />
              </svg>
            </div>
            <h2 className="text-3xl font-bold text-gray-900 tracking-tight">Create Account</h2>
            <p className="mt-2 text-sm text-gray-500">Set up your employee profile</p>
          </div>

          <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
            {errors.submit && (
              <div className="bg-red-50 border border-red-100 text-red-600 px-4 py-3 rounded-lg text-sm flex items-center">
                <svg className="w-4 h-4 mr-2 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                {errors.submit}
              </div>
            )}

            <div className="space-y-5">
              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div>
                  <label htmlFor="name" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                    Full Name
                  </label>
                  <input
                    id="name"
                    name="name"
                    type="text"
                    required
                    className="appearance-none block w-full px-3 py-3 border border-gray-200 rounded-lg placeholder-gray-400 text-gray-900 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200 sm:text-sm bg-gray-50 focus:bg-white"
                    placeholder="John Doe"
                    value={formData.name}
                    onChange={handleChange}
                  />
                  {errors.name && <p className="text-red-500 text-xs mt-1 ml-1">{errors.name}</p>}
                </div>

                <div>
                  <label htmlFor="employeeId" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                    Employee ID
                  </label>
                  <input
                    id="employeeId"
                    name="employeeId"
                    type="text"
                    disabled
                    readOnly
                    value={generatedEmployeeId}
                    className="appearance-none block w-full px-3 py-3 border border-gray-200 rounded-lg text-gray-500 bg-gray-100 cursor-not-allowed sm:text-sm font-mono"
                    placeholder="Auto-generated"
                  />
                </div>
              </div>

              <div>
                <label htmlFor="email" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                  Email
                </label>
                <input
                  id="email"
                  name="email"
                  type="email"
                  required
                  className="appearance-none block w-full px-3 py-3 border border-gray-200 rounded-lg placeholder-gray-400 text-gray-900 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200 sm:text-sm bg-gray-50 focus:bg-white"
                  placeholder="john@tapacademy.com"
                  value={formData.email}
                  onChange={handleChange}
                />
                {errors.email && <p className="text-red-500 text-xs mt-1 ml-1">{errors.email}</p>}
              </div>

              <div>
                <label htmlFor="password" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                  Password
                </label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  required
                  minLength={6}
                  className="appearance-none block w-full px-3 py-3 border border-gray-200 rounded-lg placeholder-gray-400 text-gray-900 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200 sm:text-sm bg-gray-50 focus:bg-white"
                  placeholder="•••••••• (min 6 chars)"
                  value={formData.password}
                  onChange={handleChange}
                />
                {errors.password && <p className="text-red-500 text-xs mt-1 ml-1">{errors.password}</p>}
              </div>

              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div>
                  <label htmlFor="role" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                    Role
                  </label>
                  <select
                    id="role"
                    name="role"
                    className="block w-full px-3 py-3 border border-gray-200 bg-gray-50 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent sm:text-sm"
                    value={formData.role}
                    onChange={handleChange}
                  >
                    <option value="employee">Developer/Staff</option>
                    <option value="manager">Manager</option>
                  </select>
                </div>

                <div>
                  <label htmlFor="department" className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                    Department
                  </label>
                  <select
                    id="department"
                    name="department"
                    required
                    className="block w-full px-3 py-3 border border-gray-200 bg-gray-50 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent sm:text-sm"
                    value={formData.department}
                    onChange={handleChange}
                  >
                    <option value="">Select Department</option>
                    {departmentsLoading ? (
                      <option disabled>Loading departments...</option>
                    ) : (
                      departmentsData?.data?.map((dept) => (
                        <option key={dept._id} value={dept.name}>
                          {dept.name}
                        </option>
                      ))
                    )}
                  </select>
                  {errors.department && <p className="text-red-500 text-xs mt-1 ml-1">{errors.department}</p>}
                </div>
              </div>
            </div>

            <div>
              <button
                type="submit"
                disabled={isLoading}
                className="group relative w-full flex justify-center py-3 px-4 border border-transparent text-sm font-bold rounded-lg text-white bg-[#8e24aa] hover:bg-[#7b1fa2] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 disabled:opacity-50 transition-all duration-200 shadow-md hover:shadow-lg transform hover:-translate-y-0.5"
              >
                {isLoading ? 'Creating Account...' : 'Create Account'}
              </button>
            </div>

            <div className="flex flex-col items-center space-y-2 pt-4">
              <span className="text-sm text-gray-500">Already have an account?</span>
              <div className="flex space-x-4 text-sm">
                <button
                  type="button"
                  onClick={() => navigate('/login', { state: { role: 'employee' } })}
                  className="font-medium text-purple-600 hover:text-purple-500 transition-colors"
                >
                  Employee Login
                </button>
                <span className="text-gray-300">|</span>
                <button
                  type="button"
                  onClick={() => navigate('/login', { state: { role: 'manager' } })}
                  className="font-medium text-purple-600 hover:text-purple-500 transition-colors"
                >
                  Manager Login
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}

export default Register
